### ISSUE TITLE
Compile problem: "Field sun.awt.X11GraphicsConfig.screen not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath"

### ISSUE THREAD

**Issue by rubyFeedback** [praj-foss/swing-graalvm-demo#1]
[demo:11936]    classlist:   3,087.11 ms,  0.96 GB
[demo:11936]        setup:     501.18 ms,  0.96 GB
Error: Error parsing JNI configuration in /Depot/jjj/ACK/swing-graalvm-demo/config/jni-config.json:
Field sun.awt.X11GraphicsConfig.screen not found. To allow unresolvable reflection configuration, use option --allow-incomplete-classpath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[demo:11936]      [total]:   3,672.84 ms,  0.96 GB
# Printing build artifacts to: /Depot/jjj/ACK/swing-graalvm-demo/demo.build_artifacts.txt
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1762)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1473)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1434)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1421)

---------

Would it be possible to add a link towards the JNI stuff, in the main README as-is?

I'll look at the blog post, but blog posts may disappear eventually so ... may be better
to integrate this into the main README as-is if it is not too much trouble.

**Comment by miurahr** [comment]
@rubyFeedback  You looks trying with Graalvm-CE-Java17-22.0.0.2 and I also got similar error message.
When building with `--allow-incomplete-classpath` then I got link error
```
/usr/bin/ld: /home/miurahr/.jdks/graalvm-ce-java17-22.0.0.2/lib/static/linux-amd64/glibc/libawt.a(awt_LoadLibrary.o):(.bss.jvm+0x0): multiple definition of `jvm'; /home/miurahr/.jdks/graalvm-ce-java17-22.0.0.2/lib/static/linux-amd64/glibc/libawt_xawt.a(XlibWrapper.o):(.bss.jvm+0x0): first defined here
```

I can run it  well with Graalvm-CE-Java11-22.0.0.2 like as follows:

```
Creating native image ... 
Executing [
/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.event=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.loader=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.logger=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.module=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.org.xml.sax.helpers=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.perf=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml.impl=ALL-UNNAMED \
--add-exports=java.base/jdk.internal.util.xml=ALL-UNNAMED \
--add-exports=java.base/sun.invoke.util=ALL-UNNAMED \
--add-exports=java.base/sun.net=ALL-UNNAMED \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.annotation=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.repository=ALL-UNNAMED \
--add-exports=java.base/sun.reflect.generics.tree=ALL-UNNAMED \
--add-exports=java.base/sun.security.jca=ALL-UNNAMED \
--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
--add-exports=java.base/sun.security.ssl=ALL-UNNAMED \
--add-exports=java.base/sun.security.util=ALL-UNNAMED \
--add-exports=java.base/sun.text.spi=ALL-UNNAMED \
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED \
--add-exports=java.base/sun.util.locale.provider=ALL-UNNAMED \
--add-exports=java.base/sun.util.resources=ALL-UNNAMED \
--add-exports=java.management/sun.management=ALL-UNNAMED \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=ALL-UNNAMED \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.events=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.consumer=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=ALL-UNNAMED \
--add-exports=jdk.jfr/jdk.jfr.internal=ALL-UNNAMED \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.0.0.2 \
-Dorg.graalvm.config=CE \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Djava.awt.headless=false \
-Xmx7G \
-javaagent:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/svm.jar \
-cp \
/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/native-image-base.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/javacpp-shadowed.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/pointsto.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/objectfile.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/svm.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/svm-llvm.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/builder/llvm-wrapper-shadowed.jar \
--module-path \
/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/truffle/truffle-api.jar \
'com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus' \
-watchpid \
116821 \
-imagecp \
/home/miurahr/Projects/swing-graalvm-demo/flatlaf-demo.jar:/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/library-support.jar \
-H:Path=/home/miurahr/Projects/swing-graalvm-demo \
-H:FallbackThreshold=0 \
-H:+AllowIncompleteClasspath \
-H:ConfigurationFileDirectories=config \
'-H:Class@manifest from file:///home/miurahr/Projects/swing-graalvm-demo/flatlaf-demo.jar=com.formdev.flatlaf.demo.FlatLafDemo' \
'-H:Name@manifest from file:///home/miurahr/Projects/swing-graalvm-demo/flatlaf-demo.jar=flatlaf-demo' \
-H:CLibraryPath=/home/miurahr/.jdks/graalvm-ce-java11-22.0.0.2/lib/svm/clibraries/linux-amd64 \
'-H:Name@explicit image name=demo'
]
===========================================================================================================
GraalVM Native Image: Generating 'demo'...
===========================================================================================================
[1/7] Initializing...                                                                       (5.3s @ 0.23GB)
 Version info: 'GraalVM 22.0.0.2 Java 11 CE'
[2/7] Performing analysis...  [**********]                                                 (52.9s @ 2.36GB)
   9,787 (87.17%) of 11,227 classes reachable
  22,886 (83.03%) of 27,563 fields reachable
  58,278 (63.85%) of 91,267 methods reachable
     444 classes,    40 fields, and   612 methods registered for reflection
     154 classes,   252 fields, and   126 methods registered for JNI access
[3/7] Building universe...                                                                  (4.2s @ 2.47GB)
[4/7] Parsing methods...      [**]                                                          (2.9s @ 2.74GB)
[5/7] Inlining methods...     [*****]                                                       (6.6s @ 1.85GB)
[6/7] Compiling methods...    [******]                                                     (38.1s @ 2.74GB)
[7/7] Creating image...                                                                     (4.3s @ 2.59GB)
  28.47MB (50.57%) for code area:   39,798 compilation units
  21.22MB (37.70%) for image heap:   7,018 classes and 237,352 objects
   6.61MB (11.74%) for other data
  56.30MB in total
-----------------------------------------------------------------------------------------------------------
Top 10 packages in code area:                        Top 10 object types in image heap:
   1.85MB sun.awt.X11                                   9.11MB byte[] for general heap data
   1.15MB javax.swing.plaf.nimbus                       2.75MB java.lang.Class
   1.14MB javax.swing.plaf.basic                        2.21MB java.lang.String
   1.08MB javax.swing                                   1.53MB byte[] for java.lang.String
   1.03MB com.sun.media.sound                         481.27KB java.util.HashMap$Node
 870.35KB java.util                                   444.80KB java.lang.String[]
 805.69KB sun.font                                    371.99KB com.oracle.svm.core.util.LazyFinalReference
 803.93KB java.awt                                    359.07KB byte[] for method metadata
 717.56KB javax.swing.text.html                       300.97KB java.util.HashMap$Node[]
 602.23KB javax.swing.text                            297.38KB c.o.s.c.h.DynamicHub$$Lam~af6a7fe68cfc2a1f
      ... 293 additional packages                          ... 1346 additional object types
                                    (use GraalVM Dashboard to see all)
-----------------------------------------------------------------------------------------------------------
                 12.2s (10.1% of total time) in 63 GCs | Peak RSS: 5.67GB | CPU load: 6.25
-----------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/miurahr/Projects/swing-graalvm-demo/demo (executable)
 /home/miurahr/Projects/swing-graalvm-demo/demo.build_artifacts.txt
===========================================================================================================
Finished generating 'demo' in 1m 59s.
```


Here is a summary log on GraalVM-CE-Java17
```
===========================================================================================================
GraalVM Native Image: Generating 'demo'...
===========================================================================================================
[1/7] Initializing...                                                                       (4.8s @ 0.22GB)
Warning: Field sun.awt.X11GraphicsConfig.screen not found.
 Version info: 'GraalVM 22.0.0.2 Java 17 CE'
[2/7] Performing analysis...  [**********]                                                 (51.7s @ 2.57GB)
  10,096 (87.91%) of 11,484 classes reachable
  23,324 (81.54%) of 28,605 fields reachable
  59,896 (63.00%) of 95,069 methods reachable
     457 classes,   133 fields, and   782 methods registered for reflection
     154 classes,   251 fields, and   126 methods registered for JNI access
[3/7] Building universe...                                                                  (4.0s @ 2.65GB)
[4/7] Parsing methods...      [**]                                                          (3.0s @ 2.92GB)
[5/7] Inlining methods...     [*****]                                                       (7.2s @ 1.91GB)
[6/7] Compiling methods...    [******]                                                     (38.7s @ 2.13GB)
[7/7] Creating image...
Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
```
